# Generated by Django 4.2.6 on 2023-10-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('travel_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RfqService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('members', models.IntegerField()),
                ('rfq_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqservice_rfqcategory', to='agent.rfq')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqservice_rfqservice', to='vendor.service')),
            ],
        ),
        migrations.CreateModel(
            name='RfqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqcategory_category', to='administrator.category')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqcategory_rfq', to='agent.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('agency_name', models.CharField(max_length=200)),
                ('agent_address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=20)),
                ('logo_url', models.URLField()),
                ('trade_license_url', models.URLField()),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
