# Generated by Django 4.2.6 on 2023-12-02 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqservice_rfqservice', to='vendor.service'),
        ),
        migrations.AddField(
            model_name='rfqcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqcategory_category', to='commons.category'),
        ),
        migrations.AddField(
            model_name='rfqcategory',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqcategory_rfq', to='agent.rfq'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
