# Generated by Django 4.2.6 on 2023-10-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
