# Generated by Django 4.2.6 on 2023-10-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rfq_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqservice',
            name='rfq_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqservice_rfqcategory', to='agent.rfqcategory'),
        ),
    ]
