# Generated by Django 4.2.6 on 2024-01-03 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
