# Generated by Django 4.2.6 on 2023-11-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqservice_rfqservice', to='vendor.service'),
        ),
    ]
