# Generated by Django 4.2.6 on 2023-11-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq',
            name='assigned_on',
            field=models.DateTimeField(blank=True, default='2023-11-07 13:09:37.698350'),
            preserve_default=False,
        ),
    ]
