# Generated by Django 4.2.6 on 2024-01-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqservice',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfqservice',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
