# Generated by Django 4.2.6 on 2023-10-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_rfqservice_rfq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
