# Generated by Django 4.2.6 on 2024-01-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rfq_customer_alter_rfq_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqservice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rfqservice',
            name='hotel_name',
        ),
        migrations.AddField(
            model_name='agent',
            name='pseudo_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfqservice',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfqservice',
            name='travel_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agency_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='trade_license_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfqservice',
            name='depart_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfqservice',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
