# Generated by Django 4.2.6 on 2023-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rfq_assigned_rfq_assigned_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='assigned',
        ),
        migrations.AlterField(
            model_name='rfq',
            name='assigned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('assigned', 'assigned'), ('updated', 'updated'), ('declined', 'declined')], default='pending', max_length=20),
        ),
    ]
