# Generated by Django 4.2.6 on 2023-11-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_rfqservice_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfq',
            old_name='assigned_on',
            new_name='approved_on',
        ),
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('updated', 'updated'), ('declined', 'declined')], default='pending', max_length=20),
        ),
    ]
