# Generated by Django 4.2.6 on 2023-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_rename_assigned_on_rfq_approved_on_alter_rfq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqservice',
            name='adult_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfqservice',
            name='child_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfqservice',
            name='infant_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rfqservice',
            name='members',
            field=models.IntegerField(default=0),
        ),
    ]
