# Generated by Django 4.2.6 on 2023-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_rfq_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('updated', 'updated'), ('declined', 'declined')], default='pending', max_length=20),
        ),
    ]
