# Generated by Django 4.2.6 on 2023-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_rfqservice_adult_members_rfqservice_child_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqservice',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
