# Generated by Django 4.2.6 on 2023-11-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_rfqservice_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
