# Generated by Django 4.2.6 on 2023-11-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_alter_rfq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqservice',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
