# Generated by Django 4.2.6 on 2023-11-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_rfqservice_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rfqservice',
            name='admin_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rfqservice',
            name='agent_commission',
            field=models.FloatField(default=0),
        ),
    ]
