# Generated by Django 4.2.6 on 2023-11-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_agent_commission_rfqservice_admin_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('confirmed', 'confirmed'), ('declined', 'declined'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
