# Generated by Django 4.2.6 on 2023-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='password_txt',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
