# Generated by Django 4.2.6 on 2024-01-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=20),
        ),
    ]
