# Generated by Django 4.2.6 on 2024-01-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
