# Generated by Django 4.2.6 on 2023-12-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('vendor_bill', 'vendor_bill'), ('admin_bill', 'admin_bill'), ('agent_bill', 'agent_bill'), ('admin_paid', 'admin_paid'), ('vendor_paid', 'vendor_paid')], default='vendor_bill', max_length=20),
        ),
    ]
