# Generated by Django 4.2.6 on 2024-01-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='admin_due',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='agent_billed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='agent_due',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status_1',
            field=models.CharField(choices=[('admin_bill', 'admin_bill'), ('agent_bill', 'agent_bill'), ('admin_paid', 'admin_paid')], default='admin_bill', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
